spring:
  application:
    name: siman-marvelpedia-ws
  datasource:
    url: ${DBURI}
    password: ${DBPASS}
    username: ${DBUSER}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secret: ${JWTSECRET}
  exp-time: 86400000 #24 Horas
server:
  servlet:
    context-path: /marvelpedia

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [${PID}] ---  %-40.40logger{0} : %m%n"