spring:
  application:
    name: siman-marvelpedia-ws
  datasource:
    url: ${DBURI}
    password: ${DBPASS}
    username: ${DBUSER}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secret: ${JWTSECRET}
  exp-time: 86400000 #24 Horas
server:
  servlet:
    context-path: /marvelpedia